apiVersion: v1
kind: Secret
metadata:
  name: azure-devops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://dev.azure.com/myorg/myproject/_git/config-repo
  username: git
  password: <AZURE_DEVOPS_PAT>
