apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-alerts
  namespace: argocd
spec:
  groups:
    - name: argocd
      interval: 30s
      rules:
        - alert: ArgoCDSyncFailure
          expr: |
            argocd_app_info{sync_status="OutOfSync"} == 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "ArgoCD application out of sync"
            description: "Application {{ $labels.name }} in {{ $labels.namespace }} is out of sync"
        
        - alert: ArgoCDAppUnhealthy
          expr: |
            argocd_app_info{health_status!="Healthy"} == 1
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: "ArgoCD application unhealthy"
            description: "Application {{ $labels.name }} health status is {{ $labels.health_status }}"
